services:
  app:
    build:
      context: ..
      dockerfile: LoreCommander/docker/Dockerfile
    container_name: lorecommander_app
    ports:
      - "8080:80"
    volumes:
      - ../LoreCommander:/var/www/html/LoreCommander
      - ../Zermelo:/var/www/html/Zermelo
      - ../DURC:/var/www/html/DURC
      # Mount a volume for the local image cache
      - lorecommander_imgdata:/var/www/html/LoreCommander/public/imgdata
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    image: mariadb:10.5
    container_name: lorecommander_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - lorecommander_db_data:/var/lib/mysql

volumes:
  lorecommander_db_data:
  lorecommander_imgdata:
