<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

lore.arttag by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in arttag.php 

*/

class arttag extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'lore.arttag';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'excludes_arttag', //from from many
			'cardface_classofcreature_arttag', //from from many
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'arttag_name' => 'varchar',
		'is_directed' => 'tinyint',
		'excludes_arttag_id' => 'int',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
			]; //end field_type_map

		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

/**
*	get all the excludes_arttag for this arttag
*/
	public function excludes_arttag(){
		return $this->hasMany('App\arttag','excludes_arttag_id','id');
	}


/**
*	get all the cardface_classofcreature_arttag for this arttag
*/
	public function cardface_classofcreature_arttag(){
		return $this->hasMany('App\cardface_classofcreature_arttag','arttag_id','id');
	}


		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

		//DURC would have added excludes_arttag but it was already used in has_many. 
		//You will have to resolve these recursive relationships in your code.

//Originating SQL Schema
/*
CREATE TABLE `lore`.`arttag` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `arttag_name` varchar(255) NOT NULL,
  `is_directed` tinyint(1) NOT NULL DEFAULT 0,
  `excludes_arttag_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `tag_name` (`arttag_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8
*/


}//end of arttag