<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

lore.classofc_classofc_vspack by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in classofc_classofc_vspack.php 

*/

class classofc_classofc_vspack extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'lore.classofc_classofc_vspack';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'classofc', //from belongs to
			'second_classofc', //from belongs to
			'vspack', //from belongs to
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'classofc_id' => 'int',
		'second_classofc_id' => 'int',
		'vspack_id' => 'int',
		'is_bulk_linker' => 'tinyint',
		'link_note' => 'varchar',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
			]; //end field_type_map

		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

/**
*	get the single classofc for this classofc_classofc_vspack
*/
	public function classofc(){
		return $this->belongsTo('App\classofc','classofc_id','id');
	}


/**
*	get the single second_classofc for this classofc_classofc_vspack
*/
	public function second_classofc(){
		return $this->belongsTo('App\classofc','second_classofc_id','id');
	}


/**
*	get the single vspack for this classofc_classofc_vspack
*/
	public function vspack(){
		return $this->belongsTo('App\vspack','vspack_id','id');
	}



//Originating SQL Schema
/*
CREATE TABLE `lore`.`classofc_classofc_vspack` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `classofc_id` int(11) NOT NULL,
  `second_classofc_id` int(11) NOT NULL,
  `vspack_id` int(11) NOT NULL,
  `is_bulk_linker` tinyint(1) NOT NULL DEFAULT 0,
  `link_note` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `classofc_id` (`classofc_id`,`second_classofc_id`,`vspack_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8
*/


}//end of classofc_classofc_vspack