<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

lore.mtgset by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in mtgset.php 

*/

class mtgset extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'lore.mtgset';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'scryfall_identifier' => 'varchar',
		'code' => 'varchar',
		'mtgo_code' => 'varchar',
		'tcgplayer_id' => 'int',
		'name' => 'varchar',
		'set_type' => 'varchar',
		'released_at' => 'varchar',
		'block_code' => 'varchar',
		'block' => 'varchar',
		'parenth_set_code' => 'varchar',
		'card_count' => 'int',
		'is_digital' => 'tinyint',
		'is_foil_only' => 'tinyint',
		'scryfall_url' => 'varchar',
		'set_url' => 'varchar',
		'icon_svg_url' => 'varchar',
		'search_url' => 'varchar',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
			]; //end field_type_map

		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `lore`.`mtgset` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `scryfall_identifier` varchar(255) NOT NULL,
  `code` varchar(5) NOT NULL,
  `mtgo_code` varchar(255) DEFAULT NULL,
  `tcgplayer_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `set_type` varchar(255) NOT NULL,
  `released_at` varchar(255) NOT NULL,
  `block_code` varchar(255) NOT NULL,
  `block` varchar(255) NOT NULL,
  `parenth_set_code` varchar(255) NOT NULL,
  `card_count` int(11) NOT NULL,
  `is_digital` tinyint(1) NOT NULL,
  `is_foil_only` tinyint(1) NOT NULL,
  `scryfall_url` varchar(255) NOT NULL,
  `set_url` varchar(255) NOT NULL,
  `icon_svg_url` varchar(255) NOT NULL,
  `search_url` varchar(255) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1
*/


}//end of mtgset