<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
/*
	Note this class was auto-generated from 

DURC_irs.nonprofitcorp by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in nonprofitcorp.php 

*/

class nonprofitcorp extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'DURC_irs.nonprofitcorp';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'EIN' => 'int',
		'TAXPAYER_NAME' => 'varchar',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required form elements
    protected $non_nullable_fields = [
		'id',
		'EIN',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'id' => null,
		'EIN' => '0',
		'TAXPAYER_NAME' => 'NULL',
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'id' => 'integer|required',
		'EIN' => 'integer',
		'TAXPAYER_NAME' => 'nullable',
	]; // End of validation rules
		
        
	// These are mutators generated for all model attributes.
	// Mutators are called implicitly when getting and setting the attribute
	public function getIdAttribute($value)
	{
		$formatted_value = $value;
		return $formatted_value;
	}

	public function setIdAttribute($value)
	{
		$formatted_value = DURC::formatForStorage('id', 'int', $value, $this);
		$this->attributes['id'] = $formatted_value;
	}

	public function getEINAttribute($value)
	{
		$formatted_value = $value;
		return $formatted_value;
	}

	public function setEINAttribute($value)
	{
		$formatted_value = DURC::formatForStorage('EIN', 'int', $value, $this);
		$this->attributes['EIN'] = $formatted_value;
	}

	public function getTAXPAYERNAMEAttribute($value)
	{
		$formatted_value = $value;
		return $formatted_value;
	}

	public function setTAXPAYERNAMEAttribute($value)
	{
		$formatted_value = DURC::formatForStorage('TAXPAYER_NAME', 'varchar', $value, $this);
		$this->attributes['TAXPAYER_NAME'] = $formatted_value;
	}

 
        
		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `DURC_irs`.`nonprofitcorp` (
  `id` int(11) NOT NULL,
  `EIN` int(9) NOT NULL DEFAULT 0,
  `TAXPAYER_NAME` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1
*/


}//end of nonprofitcorp