<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
/*
	Note this class was auto-generated from 

lore.person by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in person.php 

*/

class person extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'lore.person';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'cardface_person_atag', //from from many
			'person_classofcreature_tag', //from from many
			'person_creature_tag', //from from many
			'person_strategy_strategytag', //from from many
			'person_strategy_tag', //from from many
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'last_name' => 'varchar',
		'first_name' => 'varchar',
		'image_uri' => 'varchar',
		'wallpaper_download_url' => 'varchar',
		'mtgwiki_url' => 'varchar',
		'wizards_story_url' => 'varchar',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
			]; //end field_type_map

		//everything is fillable by default
		protected $guarded = [];


		
//DURC HAS_MANY SECTION

/**
*	get all the cardface_person_atag for this person
*/
	public function cardface_person_atag(){
		return $this->hasMany('App\cardface_person_atag','person_id','id');
	}


/**
*	get all the person_classofcreature_tag for this person
*/
	public function person_classofcreature_tag(){
		return $this->hasMany('App\person_classofcreature_tag','person_id','id');
	}


/**
*	get all the person_creature_tag for this person
*/
	public function person_creature_tag(){
		return $this->hasMany('App\person_creature_tag','person_id','id');
	}


/**
*	get all the person_strategy_strategytag for this person
*/
	public function person_strategy_strategytag(){
		return $this->hasMany('App\person_strategy_strategytag','person_id','id');
	}


/**
*	get all the person_strategy_tag for this person
*/
	public function person_strategy_tag(){
		return $this->hasMany('App\person_strategy_tag','person_id','id');
	}


		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `lore`.`person` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `last_name` varchar(100) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `image_uri` varchar(255) DEFAULT NULL,
  `wallpaper_download_url` varchar(500) DEFAULT NULL,
  `mtgwiki_url` varchar(255) DEFAULT NULL,
  `wizards_story_url` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `last_name` (`last_name`,`first_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8
*/


}//end of person