<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
use OwenIt\Auditing\Contracts\Auditable;
/*
	Note this class was auto-generated from 

lore.person by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in person.php 

*/

class person extends DURCModel  implements Auditable {

	 use \OwenIt\Auditing\Auditable; // configured using is_auditable = 1 in config json

    

    
        // the datbase for this model
        protected $table = 'lore.person';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'cardface_person_atag', //from from many
			'person_classofc_cardface', //from from many
			'person_classofc_tag', //from from many
			'person_creature_tag', //from from many
			'person_strategy_strategytag', //from from many
			'person_strategy_tag', //from from many
			'emblematic_theme', //from from many
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'last_name' => 'varchar',
		'first_name' => 'varchar',
		'person_blurb' => 'varchar',
		'image_uri' => 'varchar',
		'wallpaper_download_url' => 'varchar',
		'mtgwiki_url' => 'varchar',
		'wizards_story_url' => 'varchar',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required/present form elements
    protected $non_nullable_fields = [
		'id',
		'last_name',
		'first_name',
		'person_blurb',
		'created_at',
		'updated_at',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'id' => null,
		'last_name' => null,
		'first_name' => null,
		'person_blurb' => null,
		'image_uri' => 'NULL',
		'wallpaper_download_url' => 'NULL',
		'mtgwiki_url' => 'NULL',
		'wizards_story_url' => 'NULL',
		'created_at' => 'current_timestamp()',
		'updated_at' => 'current_timestamp()',
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'last_name' => 'required',
		'first_name' => 'required',
		'person_blurb' => 'required',
		'image_uri' => 'url|nullable',
		'wallpaper_download_url' => 'url|nullable',
		'mtgwiki_url' => 'url|nullable',
		'wizards_story_url' => 'url|nullable',
	]; // End of validation rules
		        
		
//DURC HAS_MANY SECTION

/**
*	get all the cardface_person_atag for this person
*/
	public function cardface_person_atag(){
		return $this->hasMany('App\cardface_person_atag','person_id','id');
	}


/**
*	get all the person_classofc_cardface for this person
*/
	public function person_classofc_cardface(){
		return $this->hasMany('App\person_classofc_cardface','person_id','id');
	}


/**
*	get all the person_classofc_tag for this person
*/
	public function person_classofc_tag(){
		return $this->hasMany('App\person_classofc_tag','person_id','id');
	}


/**
*	get all the person_creature_tag for this person
*/
	public function person_creature_tag(){
		return $this->hasMany('App\person_creature_tag','person_id','id');
	}


/**
*	get all the person_strategy_strategytag for this person
*/
	public function person_strategy_strategytag(){
		return $this->hasMany('App\person_strategy_strategytag','person_id','id');
	}


/**
*	get all the person_strategy_tag for this person
*/
	public function person_strategy_tag(){
		return $this->hasMany('App\person_strategy_tag','person_id','id');
	}


/**
*	get all the emblematic_theme for this person
*/
	public function emblematic_theme(){
		return $this->hasMany('App\theme','emblematic_person_id','id');
	}


		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `lore`.`person` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `last_name` varchar(100) NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `person_blurb` varchar(2000) NOT NULL,
  `image_uri` varchar(255) DEFAULT NULL,
  `wallpaper_download_url` varchar(500) DEFAULT NULL,
  `mtgwiki_url` varchar(255) DEFAULT NULL,
  `wizards_story_url` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `last_name` (`last_name`,`first_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8
*/


}//end of person