<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
use OwenIt\Auditing\Contracts\Auditable;
/*
	Note this class was auto-generated from 

DURC_northwind_data.purchaseOrderDetail by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in purchaseorderdetail.php 

*/

class purchaseorderdetail extends DURCModel {

	

    

    
        // the datbase for this model
        protected $table = 'DURC_northwind_data.purchaseOrderDetail';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'purchaseorder', //from belongs to
			'product', //from belongs to
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'purchaseOrder_id' => 'int',
		'product_id' => 'int',
		'quantity' => 'decimal',
		'unitCost' => 'decimal',
		'dateReceived' => 'datetime',
		'postedToInventory' => 'tinyint',
		'inventory_id' => 'int',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required/present form elements
    protected $non_nullable_fields = [
		'id',
		'purchaseOrder_id',
		'quantity',
		'unitCost',
		'postedToInventory',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'id' => null,
		'purchaseOrder_id' => null,
		'product_id' => 'NULL',
		'quantity' => null,
		'unitCost' => null,
		'dateReceived' => 'NULL',
		'postedToInventory' => '0',
		'inventory_id' => 'NULL',
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'purchaseOrder_id' => 'integer|required',
		'product_id' => 'integer|nullable',
		'quantity' => 'numeric|required',
		'unitCost' => 'numeric|required',
		'dateReceived' => 'nullable',
		'postedToInventory' => 'integer',
		'inventory_id' => 'integer|nullable',
	]; // End of validation rules
		        
		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

/**
*	get the single purchaseorder for this purchaseorderdetail
*/
	public function purchaseorder(){
		return $this->belongsTo('App\purchaseorder','purchaseOrder_id','id');
	}


/**
*	get the single product for this purchaseorderdetail
*/
	public function product(){
		return $this->belongsTo('App\product','product_id','id');
	}



//Originating SQL Schema
/*
CREATE TABLE `DURC_northwind_data`.`purchaseOrderDetail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `purchaseOrder_id` int(11) NOT NULL,
  `product_id` int(11) DEFAULT NULL,
  `quantity` decimal(18,4) NOT NULL,
  `unitCost` decimal(19,4) NOT NULL,
  `dateReceived` datetime DEFAULT NULL,
  `postedToInventory` tinyint(1) NOT NULL DEFAULT 0,
  `inventory_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `id` (`id`),
  KEY `inventory_id` (`inventory_id`),
  KEY `purchaseOrder_id` (`purchaseOrder_id`),
  KEY `product_id` (`product_id`),
  CONSTRAINT `fkPurchaseOrderDetailInventoryTransaction1` FOREIGN KEY (`inventory_id`) REFERENCES `inventoryTransaction` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fkPurchaseOrderDetailProducts1` FOREIGN KEY (`product_id`) REFERENCES `northwind_model`.`product` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fkPurchaseOrderDetailPurchaseOrder1` FOREIGN KEY (`purchaseOrder_id`) REFERENCES `purchaseOrder` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB  DEFAULT CHARSET=utf8
*/


}//end of purchaseorderdetail