<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
/*
	Note this class was auto-generated from 

DURC_northwind_model.salesReport by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in salesreport.php 

*/

class salesreport extends DURCModel{

    protected $primaryKey = 'groupBy';

    
        // the datbase for this model
        protected $table = 'DURC_northwind_model.salesReport';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'groupBy' => 'varchar',
		'display' => 'varchar',
		'title' => 'varchar',
		'filterRowSource' => 'longtext',
		'default' => 'tinyint',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required form elements
    protected $non_nullable_fields = [
		'groupBy',
		'default',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'groupBy' => null,
		'display' => 'NULL',
		'title' => 'NULL',
		'filterRowSource' => 'NULL',
		'default' => '0',
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'groupBy' => 'required',
		'display' => 'nullable',
		'title' => 'nullable',
		'filterRowSource' => 'nullable',
	]; // End of validation rules
		
        
	// These are mutators generated for all model attributes.
	// Mutators are called implicitly when getting and setting the attribute
	public function getGroupByAttribute($value)
	{
		$formatted_value = $value;
		return $formatted_value;
	}

	public function setGroupByAttribute($value)
	{
		$formatted_value = DURC::formatForStorage('groupBy', 'varchar', $value, $this);
		$this->attributes['groupBy'] = $formatted_value;
	}

	public function getDisplayAttribute($value)
	{
		$formatted_value = $value;
		return $formatted_value;
	}

	public function setDisplayAttribute($value)
	{
		$formatted_value = DURC::formatForStorage('display', 'varchar', $value, $this);
		$this->attributes['display'] = $formatted_value;
	}

	public function getTitleAttribute($value)
	{
		$formatted_value = $value;
		return $formatted_value;
	}

	public function setTitleAttribute($value)
	{
		$formatted_value = DURC::formatForStorage('title', 'varchar', $value, $this);
		$this->attributes['title'] = $formatted_value;
	}

	public function getFilterRowSourceAttribute($value)
	{
		$formatted_value = $value;
		return $formatted_value;
	}

	public function setFilterRowSourceAttribute($value)
	{
		$formatted_value = DURC::formatForStorage('filterRowSource', 'longtext', $value, $this);
		$this->attributes['filterRowSource'] = $formatted_value;
	}

	public function getDefaultAttribute($value)
	{
		$formatted_value = $value;
		return $formatted_value;
	}

	public function setDefaultAttribute($value)
	{
		$formatted_value = DURC::formatForStorage('default', 'tinyint', $value, $this);
		$this->attributes['default'] = $formatted_value;
	}

 
        
		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `DURC_northwind_model`.`salesReport` (
  `groupBy` varchar(50) NOT NULL,
  `display` varchar(50) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `filterRowSource` longtext DEFAULT NULL,
  `default` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`groupBy`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
*/


}//end of salesreport