<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
use OwenIt\Auditing\Contracts\Auditable;
/*
	Note this class was auto-generated from 

DURC_aaa.sibling by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in sibling.php 

*/

class sibling extends DURCModel {

	 //not auditable, configured using is_auditable = 0 in config json

    

    
        // the datbase for this model
        protected $table = 'DURC_aaa.sibling';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'step_sibling', //from from many
			'sibling', //from from many
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'siblingname' => 'varchar',
		'step_sibling_id' => 'int',
		'sibling_id' => 'int',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required/present form elements
    protected $non_nullable_fields = [
		'id',
		'siblingname',
		'created_at',
		'updated_at',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'id' => null,
		'siblingname' => null,
		'step_sibling_id' => 'NULL',
		'sibling_id' => 'NULL',
		'created_at' => null,
		'updated_at' => null,
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'siblingname' => 'required',
		'step_sibling_id' => 'integer|nullable',
		'sibling_id' => 'integer|nullable',
		'created_at' => 'required',
		'updated_at' => 'required',
	]; // End of validation rules
		        
		
//DURC HAS_MANY SECTION

/**
*	get all the step_sibling for this sibling
*/
	public function step_sibling(){
		return $this->hasMany('App\sibling','step_sibling_id','id');
	}


/**
*	get all the sibling for this sibling
*/
	public function sibling(){
		return $this->hasMany('App\sibling','sibling_id','id');
	}


		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

		//DURC would have added step_sibling but it was already used in has_many. 
		//You will have to resolve these recursive relationships in your code.
		//DURC would have added sibling but it was already used in has_many. 
		//You will have to resolve these recursive relationships in your code.

//Originating SQL Schema
/*
CREATE TABLE `DURC_aaa`.`sibling` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `siblingname` varchar(255) NOT NULL,
  `step_sibling_id` int(11) DEFAULT NULL,
  `sibling_id` int(11) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1
*/


}//end of sibling