<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
/*
	Note this class was auto-generated from 

DURC_aaa.test_default_date by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in test_default_date.php 

*/

class test_default_date extends DURCModel{

    

    
        // the datbase for this model
        protected $table = 'DURC_aaa.test_default_date';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'datetime_none' => 'datetime',
		'date_none' => 'date',
		'datetime_current' => 'datetime',
		'date_current' => 'varchar',
		'datetime_null' => 'datetime',
		'date_null' => 'date',
		'datetime_defined' => 'datetime',
		'date_defined' => 'date',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required/present form elements
    protected $non_nullable_fields = [
		'id',
		'datetime_none',
		'date_none',
		'datetime_current',
		'datetime_defined',
		'date_defined',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'id' => null,
		'datetime_none' => null,
		'date_none' => null,
		'datetime_current' => 'current_timestamp()',
		'date_current' => '\'Current timestamp not supported for date\'',
		'datetime_null' => 'NULL',
		'date_null' => 'NULL',
		'datetime_defined' => '\'2000-01-01 01:23:45\'',
		'date_defined' => '\'2000-01-01\'',
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'id' => 'integer|required',
		'datetime_none' => 'required',
		'date_none' => 'required',
		'date_current' => 'nullable',
		'datetime_null' => 'nullable',
		'date_null' => 'nullable',
	]; // End of validation rules
		        
		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `DURC_aaa`.`test_default_date` (
  `id` int(11) NOT NULL,
  `datetime_none` datetime NOT NULL,
  `date_none` date NOT NULL,
  `datetime_current` datetime NOT NULL DEFAULT current_timestamp(),
  `date_current` varchar(255) DEFAULT 'Current timestamp not supported for date',
  `datetime_null` datetime DEFAULT NULL,
  `date_null` date DEFAULT NULL,
  `datetime_defined` datetime NOT NULL DEFAULT '2000-01-01 01:23:45',
  `date_defined` date NOT NULL DEFAULT '2000-01-01',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
*/


}//end of test_default_date