<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
//use Owen It\Auditing\Contracts\Auditable;
/*
	Note this class was auto-generated from 

mirrulation.uniquecomment by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in uniquecomment.php 

*/

class uniquecomment extends DURCModel {

	 //not auditable, configured using is_auditable = 0 in config json

    

    
        // the datbase for this model
        protected $table = 'mirrulation.uniquecomment';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'uniquecomment_to_comment', //from from many
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'simplified_comment_text_md5' => 'varchar',
		'simplified_comment_text' => 'longtext',
		'comment_count' => 'bigint',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required/present form elements
    protected $non_nullable_fields = [
		'id',
		'simplified_comment_text',
		'comment_count',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'id' => null,
		'simplified_comment_text_md5' => 'NULL',
		'simplified_comment_text' => null,
		'comment_count' => null,
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'simplified_comment_text_md5' => 'nullable',
		'simplified_comment_text' => 'required',
		'comment_count' => 'integer|required',
	]; // End of validation rules
		        
		
//DURC HAS_MANY SECTION

/**
*	get all the uniquecomment_to_comment for this uniquecomment
*/
	public function uniquecomment_to_comment(){
		return $this->hasMany('App\uniquecomment_to_comment','uniquecomment_id','id');
	}


		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `mirrulation`.`uniquecomment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `simplified_comment_text_md5` varchar(33) DEFAULT NULL,
  `simplified_comment_text` longtext NOT NULL,
  `comment_count` bigint(21) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `simplified_comment_text_md5` (`simplified_comment_text_md5`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
*/


}//end of uniquecomment