<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
//use Owen It\Auditing\Contracts\Auditable;
/*
	Note this class was auto-generated from 

mirrulation.uniquecomment_research by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in uniquecomment_research.php 

*/

class uniquecomment_research extends DURCModel {

	 //not auditable, configured using is_auditable = 0 in config json

    protected $primaryKey = 'simplified_comment_text_md5';

    
        // the datbase for this model
        protected $table = 'mirrulation.uniquecomment_research';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
		];


	//DURC did not detect any date fields

	public $timestamps = false;
	//DURC NOTE: did not find updated_at and created_at fields for this model

	
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'simplified_comment_text_md5' => 'varchar',
		'uniquecomment_name' => 'varchar',
		'uniquecomment_org_url' => 'varchar',
		'uniquecomment_wayback_machine_url' => 'varchar',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required/present form elements
    protected $non_nullable_fields = [
		'simplified_comment_text_md5',
		'uniquecomment_name',
		'uniquecomment_org_url',
		'uniquecomment_wayback_machine_url',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'simplified_comment_text_md5' => null,
		'uniquecomment_name' => null,
		'uniquecomment_org_url' => null,
		'uniquecomment_wayback_machine_url' => null,
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'simplified_comment_text_md5' => 'required',
		'uniquecomment_name' => 'required',
		'uniquecomment_org_url' => 'url|required',
		'uniquecomment_wayback_machine_url' => 'url|required',
	]; // End of validation rules
		        
		
//DURC HAS_MANY SECTION

			//DURC did not detect any has_many relationships
		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `mirrulation`.`uniquecomment_research` (
  `simplified_comment_text_md5` varchar(33) NOT NULL,
  `uniquecomment_name` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `uniquecomment_org_url` varchar(255) NOT NULL,
  `uniquecomment_wayback_machine_url` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`simplified_comment_text_md5`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
*/


}//end of uniquecomment_research