<?php

namespace App\DURC\Models;

use CareSet\DURC\DURCModel;
use CareSet\DURC\DURC;
//use Owen It\Auditing\Contracts\Auditable;
/*
	Note this class was auto-generated from 

lore.wallpaper by DURC.

	This class will be overwritten during future auto-generation runs..
	Itjust reflects whatever is in the database..
	DO NOT EDIT THIS FILE BY HAND!!
	Your changes go in wallpaper.php 

*/

class wallpaper extends DURCModel {

	 //not auditable, configured using is_auditable = 0 in config json

    

    
        // the datbase for this model
        protected $table = 'lore.wallpaper';

	//DURC will dymanically copy these into the $with variable... which prevents recursion problem: https://laracasts.com/discuss/channels/eloquent/eager-load-deep-recursion-problem?page=1
		protected $DURC_selfish_with = [ 
			'wallpaper_illustration', //from from many
			'wallpaper_url', //from from many
		];


	//DURC did not detect any date fields

	public $timestamps = true;
	const UPDATED_AT = 'updated_at';
	const CREATED_AT = 'created_at';
	
	

	//for many functions to work, we need to be able to do a lookup on the field_type and get back the MariaDB/MySQL column type.
	static $field_type_map = [
		'id' => 'int',
		'art_name' => 'varchar',
		'set_name' => 'varchar',
		'art_release_date' => 'datetime',
		'author_name' => 'varchar',
		'created_at' => 'datetime',
		'updated_at' => 'datetime',
	]; //end field_type_map
		
    // Indicate which fields are nullable for the UI to be able to validate required/present form elements
    protected $non_nullable_fields = [
		'id',
		'author_name',
		'updated_at',
	]; // End of nullable fields

    // Use default_values array to specify the default values for each field (if any) indicated by the DB schema, to be used as placeholder on form elements
    protected $default_values = [
		'id' => null,
		'art_name' => 'NULL',
		'set_name' => 'NULL',
		'art_release_date' => 'NULL',
		'author_name' => null,
		'created_at' => 'current_timestamp()',
		'updated_at' => 'current_timestamp()',
	];  // End of attributes
        
    //everything is fillable by default
    protected $guarded = [];
		
    // These are validation rules used by the DURCModel parent to validate data before storage
    protected static $rules = [
		'art_name' => 'nullable',
		'set_name' => 'nullable',
		'art_release_date' => 'nullable',
		'author_name' => 'required',
		'created_at' => 'nullable',
	]; // End of validation rules
		        
		
//DURC HAS_MANY SECTION

/**
*	get all the wallpaper_illustration for this wallpaper
*/
	public function wallpaper_illustration(){
		return $this->hasMany('App\wallpaper_illustration','wallpaper_id','id');
	}


/**
*	get all the wallpaper_url for this wallpaper
*/
	public function wallpaper_url(){
		return $this->hasMany('App\wallpaper_url','wallpaper_id','id');
	}


		
		
//DURC HAS_ONE SECTION

			//DURC did not detect any has_one relationships

		
//DURC BELONGS_TO SECTION

			//DURC did not detect any belongs_to relationships

//Originating SQL Schema
/*
CREATE TABLE `lore`.`wallpaper` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `art_name` varchar(190) DEFAULT NULL,
  `set_name` varchar(190) DEFAULT NULL,
  `art_release_date` datetime DEFAULT NULL,
  `author_name` varchar(190) NOT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `art_name` (`art_name`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
*/


}//end of wallpaper