<?php
/*
 * Generated configuration file
 * Generated by: Cline
 * Date: <?php echo date('Y-m-d H:i:s'); ?>
 */

$cfg['blowfish_secret'] = 'kljHkGkjhJHGkjgjhgJHGkhjgJHGFjhgJHGFjhg'; // you should change this

$i = 0;

$i++;
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['host'] = 'db';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['user'] = getenv('DB_USERNAME');
$cfg['Servers'][$i]['password'] = getenv('DB_PASSWORD');

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
