CREATE DATABASE IF NOT EXISTS _zermelo_cache;
CREATE DATABASE IF NOT EXISTS _zermelo_config;
CREATE DATABASE IF NOT EXISTS lore;
GRANT ALL PRIVILEGES ON *.* TO 'lore'@'%' IDENTIFIED BY 'ChangeMe';
FLUSH PRIVILEGES;
