<!doctype html>
<html lang="en">
<head>

    	<title>{{ $presenter->getReport()->getReportName() }}</title>
    	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    	<meta name="description" content="Cube is a map of the healthcare system">
    	<meta name="author" content="CareSet Team">

	

    	<!-- standard styles -->
	<link type="text/css" rel="stylesheet" href="/css/bootstrap.4.3.1.min.css">
    	<link type="text/css" rel="stylesheet" href="/fontawesome/css/all.css">

    	<link type="text/css" rel="stylesheet" href="/css/colors.css">
    	<link type="text/css" rel="stylesheet" href="/css/taxonomyChooser.css">
	        <!-- custom css -->
        <link type="text/css" rel="stylesheet" href="/css/colors.css"/>
        <link type="text/css" rel="stylesheet" href="/css/noselect.css"/>
        <link type="text/css" rel="stylesheet" href="/css/print.css"/>
        <link type="text/css" rel="stylesheet" href="/css/floating.feedback.css"/>

    	<!-- standard javascript -->
    	<script type="text/javascript" language="javascript" src="/js/jquery-3.4.1.min.js"></script>
	<script type="text/javascript" src="/js/bootstrap.4.3.1.min.js"></script>

  <script type='text/javascript' language='javascript' src='/js/d3.3.5.17.min.js'></script>
	<script type="text/javascript" src="/js/saveSvgAsPng.js"></script>


	<!-- custom javascript -->
	<script type="text/javascript" src="/js/util.js"></script>
	<script type="text/javascript" src="/js/careset_api.js"></script>
  	<script type="text/javascript" src="/js/html2canvas.js"></script>
  
	<!-- load our dust templates -->
	<script type='text/javascript' language="javascript" src='/js/dust-full-2.6.2.js'></script>
	<script type="text/javascript" language="javascript" src="/js/dust-helpers-1.6.2.js"></script>

	<!-- font awesome js -->
	<script type="text/javascript" language="javascript" src="/fontawesome/js/all.js"></script>

	<!-- dust_html.tpl auto generated by dc.php -->
<script src='/dust/FORCE_data_options_datasource.js?1523568832'></script> 
<script src='/dust/FORCE_data_options_tax.js?1523568832'></script> 
<script src='/dust/admin.bn_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.domainname_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.ndc9_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.npi_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.phone_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.rxnorm_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.system_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.taxcluster_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.trueaddress_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.vein_panel_dust.js?1523568832'></script> 
<script src='/dust/admin.zipcode_panel_dust.js?1523568832'></script> 
<script src='/dust/all_node_dust.js?1523568832'></script> 
<script src='/dust/bn_panel_dust.js?1523568832'></script> 
<script src='/dust/careset_attribution_dust.js?1523568832'></script> 
<script src='/dust/careset_npi_dust.js?1523568832'></script> 
<script src='/dust/cartcheckbox.js?1523568832'></script> 
<script src='/dust/cartcheckbox_big.js?1523568832'></script> 
<script src='/dust/commonwell_match_summary_dust.js?1523568832'></script> 
<script src='/dust/commonwell_matches_dust.js?1523568832'></script> 
<script src='/dust/commonwell_searchresultsPhone_dust.js?1523568832'></script> 
<script src='/dust/commonwell_searchresults_dust.js?1523568832'></script> 
<script src='/dust/domainname_panel_dust.js?1523568832'></script> 
<script src='/dust/hotlogs_panel_dust.js?1523568832'></script> 
<script src='/dust/hotlogs_report_dust.js?1523568832'></script> 
<script src='/dust/interop_demo_dust.js?1523568832'></script> 
<script src='/dust/meaningful_vendor_dust.js?1523568832'></script> 
<script src='/dust/messages_boxlist_dust.js?1523568832'></script> 
<script src='/dust/modal_dust.js?1523568832'></script> 
<script src='/dust/ndc9_panel_dust.js?1523568832'></script> 
<script src='/dust/npi_codegroup_dust.js?1523568832'></script> 
<script src='/dust/npi_dgdrgs_dust.js?1523568832'></script> 
<script src='/dust/npi_doccompare_dust.js?1523568832'></script> 
<script src='/dust/npi_drgs_dust.js?1523568832'></script> 
<script src='/dust/npi_history_dust.js?1523568832'></script> 
<script src='/dust/npi_historydrill_dust.js?1523568832'></script> 
<script src='/dust/npi_meaningful_dust.js?1523568832'></script> 
<script src='/dust/npi_meds_dust.js?1523568832'></script> 
<script src='/dust/npi_panel_dust.js?1523568832'></script> 
<script src='/dust/npi_procs_dust.js?1523568832'></script> 
<script src='/dust/npi_record_dust.js?1523568832'></script> 
<script src='/dust/npi_referredprocs_dust.js?1523568832'></script> 
<script src='/dust/npi_shared_dust.js?1523568832'></script> 
<script src='/dust/npi_sidemenu_dust.js?1523568832'></script> 
<script src='/dust/npi_specialty_dust.js?1523568832'></script> 
<script src='/dust/npi_summary_dust.js?1523568832'></script> 
<script src='/dust/npi_team_dust.js?1523568832'></script> 
<script src='/dust/npi_top_dust.js?1523568832'></script> 
<script src='/dust/npi_zipcode_dust.js?1523568832'></script> 
<script src='/dust/npinotes_all_dust.js?1523568832'></script> 
<script src='/dust/npinotes_edit_dust.js?1523568832'></script> 
<script src='/dust/npinotes_list_dust.js?1523568832'></script> 
<script src='/dust/phone_panel_dust.js?1523568832'></script> 
<script src='/dust/phone_report_dust.js?1523568832'></script> 
<script src='/dust/rxnorm_panel_dust.js?1523568832'></script> 
<script src='/dust/searchresultsID_dust.js?1523568832'></script> 
<script src='/dust/searchresultsPhone_dust.js?1523568832'></script> 
<script src='/dust/searchresultsTag_dust.js?1523568832'></script> 
<script src='/dust/searchresults_dust.js?1523568832'></script> 
<script src='/dust/sortedtable.js?1523568832'></script> 
<script src='/dust/taxcluster_panel_dust.js?1523568832'></script> 
<script src='/dust/trueaddress_panel_dust.js?1523568832'></script> 
<script src='/dust/vein_panel_dust.js?1523568832'></script> 
<script src='/dust/vein_summary_dust.js?1523568832'></script> 
<script src='/dust/wikilink.js?1523568832'></script> 
<script src='/dust/zipcode_panel_dust.js?1523568832'></script> 


<!-- end dust_html.tpl -->

    	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    	<!--[if lt IE 9]>
      		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->


 <script>
  $(document).ready(function()
       {

			

		//a function that only calls the url in data-url, and does nothing else.
		$('body').on('click','.press_url_element',function() {
//			alert('been clicked');
     			url = $(this).attr('data-url');
     			$.get(url);
			$(this).addClass("btn-success");
		});

       }
  );

  </script>

</head>
<body>

@include('Zermelo::d3graph')

</body>
</html>
